const SUPABASE_URL="https://eqjkdccqgmhulzqrfval.supabase.co";
const SUPABASE_KEY="sb_publishable_yrkjmx0yAzvDnpuhCyVlUw_9QxU7Ngk";
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
let session=null,user=null,profile=null,page="home",authMode="signin",projects=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const templates=[{icon:"🎬",title:"Cinematic",desc:"Cerita dramatis dengan nuansa film.",style:"cinematic"},{icon:"🔥",title:"Motivasi",desc:"Energi kuat untuk konten inspiratif.",style:"motivational"},{icon:"❤️",title:"Emosional",desc:"Hangat, personal, dan menyentuh.",style:"emotional"},{icon:"📚",title:"Edukasi",desc:"Materi rumit menjadi mudah dipahami.",style:"educational"},{icon:"💼",title:"Bisnis",desc:"Cerita produk dan perjalanan usaha.",style:"business"},{icon:"😂",title:"Santai",desc:"Storytelling ringan dan natural.",style:"casual"}];
const state={style:"cinematic",duration:60,format:"9:16",sceneCount:5};
async function boot(){if(!sb){renderHome();return}const {data}=await sb.auth.getSession();session=data.session;user=session?.user||null;sb.auth.onAuthStateChange(async(_e,s)=>{session=s;user=s?.user||null;await syncAuth()});await syncAuth();bindNav();renderPage(page)}
async function syncAuth(){if(user){const {data}=await sb.from("story_profiles").select("*").eq("id",user.id).maybeSingle();profile=data||{id:user.id,name:user.user_metadata?.name||user.email?.split("@")[0]||"Creator",email:user.email};$("authBtn").textContent=profile.name||"Akun";await loadProjects()}else{$("authBtn").textContent="Masuk";profile=null;projects=[]}}
function bindNav(){document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>{page=b.dataset.page;document.querySelectorAll("[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===page));renderPage(page)}));$("authBtn").onclick=()=>user?renderPage("account"):openAuth();$("historyBtn").onclick=()=>{page="projects";renderPage(page)};$("authClose").onclick=closeAuth;$("authMode").onclick=toggleAuthMode;$("authSubmit").onclick=submitAuth;$("authReset").onclick=resetPassword;$("authGoogle").onclick=googleAuth}
function renderPage(p){if(p==="home")renderHome();if(p==="create")renderCreate();if(p==="projects")renderProjects();if(p==="templates")renderTemplates();if(p==="account")renderAccount()}
function renderHome(){$("main").innerHTML='<section class="hero card"><div class="eyebrow">AI STORYTELLER</div><h1>Ceritakan. AI yang membuatnya menjadi video.</h1><p>Tulis pengalaman, ide, promosi, kesaksian, atau cerita apa pun. StoryAI menyusun naskah dan storyboard yang siap dikembangkan menjadi video vertikal.</p><div class="heroActions"><button class="btn primary" onclick="goCreate()">✦ Buat video dari cerita</button><button class="btn dark" onclick="showTemplates()">Lihat template</button></div></section><section class="section"><div class="sectionHead"><div><h2>Mulai dari satu kalimat</h2><p>Tidak perlu belajar editing terlebih dahulu.</p></div></div><div class="composer card"><textarea id="quickStory" placeholder="Contoh: Saya memulai usaha dari nol, gagal tiga kali, lalu akhirnya berhasil. Saya ingin membuat video yang membuat orang lain tidak menyerah."></textarea><div class="composerFooter"><div class="chips"><button class="chip active" onclick="quickStyle(this,'motivational')">🔥 Motivasi</button><button class="chip" onclick="quickStyle(this,'cinematic')">🎬 Cinematic</button><button class="chip" onclick="quickStyle(this,'educational')">📚 Edukasi</button></div><button class="btn primary" onclick="quickGenerate()">✨ Susun dengan AI</button></div></div></section><section class="section"><div class="sectionHead"><div><h2>Template populer</h2><p>Pilih gaya, lalu masukkan cerita.</p></div></div><div class="templates">'+templates.slice(0,3).map(templateHTML).join("")+'</div></section>'+(user?'<section class="section"><div class="sectionHead"><div><h2>Proyek terakhir</h2></div><button class="btn ghost" onclick="renderPage(\'projects\')">Lihat semua</button></div>'+(projects.slice(0,3).map(projectHTML).join("")||'<div class="card empty">Belum ada proyek. Buat video pertama Anda.</div>')+'</section>':"")}
function templateHTML(t){return '<button class="template" onclick="useTemplate(\''+t.style+'\')"><div class="templateIcon">'+t.icon+'</div><b>'+t.title+'</b><small>'+t.desc+'</small></button>'}
function quickStyle(el,style){document.querySelectorAll(".chips .chip").forEach(x=>x.classList.remove("active"));el.classList.add("active");state.style=style}
function goCreate(){page="create";renderPage(page)}
function showTemplates(){page="templates";renderPage(page)}
function useTemplate(style){state.style=style;page="create";renderPage(page)}
function quickGenerate(){const t=$("quickStory")?.value.trim();if(!t)return alert("Tulis cerita terlebih dahulu.");state.initial=t;page="create";renderCreate(true)}
function renderCreate(){const initial=esc(state.initial||"");$("main").innerHTML='<section class="sectionHead"><div><h2>Buat Video</h2><p>Ubah cerita menjadi naskah dan storyboard.</p></div></section><section class="composer card"><textarea id="storyInput" placeholder="Ceritakan ide Anda dengan bahasa biasa...">'+initial+'</textarea><div class="grid2" style="margin-top:10px"><div class="field"><label>Gaya</label><select id="styleSelect">'+templates.map(t=>'<option value="'+t.style+'" '+(t.style===state.style?"selected":"")+'>'+t.icon+" "+t.title+"</option>").join("")+'</select></div><div class="field"><label>Durasi</label><select id="durationSelect"><option value="30">30 detik</option><option value="60" selected>60 detik</option><option value="180">3 menit</option></select></div><div class="field"><label>Format</label><select id="formatSelect"><option value="9:16">9:16 — Shorts/Reels/TikTok</option><option value="1:1">1:1 — Square</option><option value="16:9">16:9 — YouTube</option></select></div><div class="field"><label>Jumlah scene</label><select id="sceneSelect"><option value="4">4 scene</option><option value="5" selected>5 scene</option><option value="7">7 scene</option></select></div></div><div class="composerFooter"><span class="notice">AI akan memecah cerita menjadi hook, alur, visual, voice-over, dan penutup.</span><button class="btn primary" onclick="generateStoryboard()">✨ Buat Storyboard</button></div></section><div id="storyboardArea" class="section"></div>'}
async function generateStoryboard(){const text=$("storyInput").value.trim();if(!text)return alert("Cerita belum diisi.");state.style=$("styleSelect").value;state.duration=Number($("durationSelect").value);state.format=$("formatSelect").value;state.sceneCount=Number($("sceneSelect").value);state.generated=null;$("storyboardArea").innerHTML='<section class="storyboard card"><div class="progress"><i style="width:65%"></i></div><p class="muted">AI sedang memahami cerita...</p></section>';let data=null;try{const r=await fetch("/api/story",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({story:text,style:state.style,duration:state.duration,format:state.format,sceneCount:state.sceneCount})});if(r.ok)data=await r.json()}catch(e){}if(!data?.scenes)data=localStoryboard(text,state);renderStoryboard(data,text)}
function localStoryboard(text,st){const clean=text.replace(/\s+/g," ").trim();const parts=clean.split(/[.!?]+/).map(x=>x.trim()).filter(Boolean);const titles=["Hook","Masalah","Perjalanan","Titik balik","Penutup"];const scenes=[];for(let i=0;i<st.sceneCount;i++){const source=parts[i%Math.max(parts.length,1)]||clean;scenes.push({title:titles[i%titles.length],voice:i===0?"Pernahkah kamu merasa "+source.toLowerCase()+"?":source+".",visual:visualFor(st.style,i),duration:Math.max(4,Math.round(st.duration/st.sceneCount))})}return{title:makeTitle(clean),caption:captionFor(st.style),scenes,source:"local"}}
function visualFor(style,i){const sets={cinematic:["wide cinematic establishing shot","close-up emotional portrait","moody journey through changing light","hopeful turning point at sunrise","clean uplifting final frame"],motivational:["person facing a difficult beginning","hands working despite obstacles","moment of failure and reflection","person standing again with confidence","bright forward-looking final shot"],emotional:["quiet intimate moment","memory of an important person","solitary reflection","warm human connection","peaceful hopeful ending"],educational:["clean concept introduction","simple visual explanation","step-by-step process","key insight highlighted","summary with clear takeaway"],business:["founder starting with limited resources","product and early work","challenge and iteration","growth and customer trust","confident brand closing"],casual:["friendly everyday scene","natural conversation","small funny obstacle","simple solution","smiling relaxed ending"]};return sets[style]?.[i%5]||sets.cinematic[i%5]}
function makeTitle(t){const words=t.split(/\s+/).slice(0,7).join(" ");return words?words.charAt(0).toUpperCase()+words.slice(1):"Cerita Baru"}
function captionFor(style){return{motivational:"Sebuah cerita tentang jatuh, bangkit, dan memilih untuk terus berjalan.",cinematic:"Satu cerita. Satu perjalanan. Satu alasan untuk terus melangkah.",emotional:"Cerita sederhana yang mungkin terasa dekat dengan hidup kita.",educational:"Ubah pengalaman menjadi pelajaran yang mudah dipahami.",business:"Perjalanan membangun sesuatu dari ide menjadi kenyataan.",casual:"Cerita ringan, dibuat lebih hidup."}[style]||"Cerita Anda, dibuat lebih hidup."}
function renderStoryboard(data,sourceText){$("storyboardArea").innerHTML='<section class="storyboard card"><div class="row" style="justify-content:space-between"><div><div class="eyebrow">STORYBOARD SIAP</div><h2 style="margin:3px 0">'+esc(data.title)+'</h2><p class="muted">'+esc(data.caption)+'</p></div><span class="notice good">'+(data.source==="local"?"Draft AI siap diedit":"AI")+'</span></div><div id="scenes">'+data.scenes.map(sceneHTML).join("")+'</div><div class="composerFooter"><button class="btn ghost" onclick="renderCreate()">← Ubah cerita</button><button class="btn primary" onclick="createProject()">🎬 Lanjut ke Video</button></div></section>';state.generated={title:data.title,caption:data.caption,scenes:data.scenes,source:data.source,sourceText:sourceText}}
function sceneHTML(s,i){return '<div class="scene"><div class="sceneNum">0'+(i+1)+'<br><small>'+esc(String(s.duration))+'s</small></div><div class="sceneText"><b>'+esc(s.title)+'</b><small>Voice-over: '+esc(s.voice)+'</small><small>Visual: '+esc(s.visual)+'</small></div><button onclick="editScene('+i+')">✎</button></div>'}
function editScene(i){const s=state.generated?.scenes?.[i]||state.currentProject?.scenes?.[i];if(!s)return;const voice=prompt("Voice-over scene:",s.voice);if(voice===null)return;const visual=prompt("Deskripsi visual scene:",s.visual);if(visual===null)return;s.voice=voice.trim()||s.voice;s.visual=visual.trim()||s.visual;renderStoryboard({title:state.generated.title,caption:state.generated.caption,scenes:state.generated.scenes,source:state.generated.source},state.generated.sourceText)}
async function createProject(){const d=state.generated;if(!d)return;const project={id:crypto.randomUUID(),title:d.title,caption:d.caption,source_text:d.sourceText,style:state.style,duration:state.duration,format:state.format,scenes:d.scenes,status:"storyboard_ready",created_at:new Date().toISOString()};if(user&&sb){const {data:row,error}=await sb.from("story_projects").insert({user_id:user.id,title:project.title,source_text:project.source_text,style:project.style,duration:project.duration,format:project.format,scenes:project.scenes,status:project.status}).select().single();if(!error&&row){project.id=row.id;project.created_at=row.created_at}else if(error)console.warn(error.message)}projects=[project,...projects.filter(x=>x.id!==project.id)];renderVideo(project)}
function sceneImage(style,i){
 const sets={
  cinematic:["https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=82"],
  motivational:["https://images.unsplash.com/photo-1526401485004-2aa7e3a4a6a1?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1200&q=82"],
  emotional:["https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1504150558240-0b4fd8946624?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=1200&q=82"],
  educational:["https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1453738773917-9c3eff1db985?auto=format&fit=crop&w=1200&q=82"],
  business:["https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=82"],
  casual:["https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1200&q=82","https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=82"]
 };
 return sets[style]?.[i%5]||sets.cinematic[i%5];
}
function loadSceneImage(url){return new Promise(resolve=>{const img=new Image();img.crossOrigin="anonymous";img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=url})}
async function prepareVoice(scene){const text=String(scene?.voice||"").trim().slice(0,480);if(!text)return null;try{const r=await fetch("/api/tts?text="+encodeURIComponent(text));if(!r.ok)return null;const b=await r.arrayBuffer();if(!b.byteLength)return null;const ac=new (window.AudioContext||window.webkitAudioContext)();const buffer=await ac.decodeAudioData(b.slice(0));return{context:ac,buffer}}catch(e){console.warn("TTS unavailable",e);return null}}
function renderVideo(project){$("main").innerHTML='<section class="sectionHead"><div><h2>Video Studio</h2><p>'+esc(project.title)+" · "+project.duration+" detik · "+project.format+'</p></div></section><section class="videoCard card"><div class="videoPreview"><div class="videoMock"><div class="big">✦</div><h3>'+esc(project.title)+'</h3><p>'+esc(project.caption)+'</p><small>Gambar nyata per scene + voice-over Bahasa Indonesia akan digunakan saat render.</small></div></div><div class="exportBar"><button id="renderRealBtn" class="btn primary" onclick="renderDemoVideo()">🎬 Buat Video + Suara</button><button class="btn" onclick="copyCaption()">▣ Salin caption</button><button class="btn" onclick="shareProject()">↗ Bagikan</button></div><div id="renderProgress" class="notice" style="margin-top:10px;display:none"><div class="row" style="justify-content:space-between;margin-bottom:7px"><b id="renderStatus">Menyiapkan video…</b><b id="renderPercent">0%</b></div><div class="progress"><i></i></div><small id="renderHint" style="display:block;margin-top:7px">Mengunduh gambar dan suara untuk setiap scene. Jangan tutup halaman.</small></div><div id="renderError" class="notice error" style="margin-top:10px;display:none"></div></section>';state.currentProject=project}
async function renderDemoVideo(){
 const p=state.currentProject,preview=document.querySelector(".videoPreview"),btn=document.querySelector("#renderRealBtn"),progress=document.querySelector("#renderProgress"),pct=document.querySelector("#renderPercent"),status=document.querySelector("#renderStatus"),errBox=document.querySelector("#renderError");
 if(!p?.scenes?.length){alert("Storyboard belum siap.");return}
 if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream){showRenderError("Browser tidak mendukung video render. Gunakan Google Chrome atau Microsoft Edge terbaru.");return}
 if(btn)btn.disabled=true;if(progress)progress.style.display="block";if(errBox)errBox.style.display="none";
 let stream=null,recorder=null,timer=null,stopTimer=null,stopped=false,chunks=[],audioCtx=null,audioDest=null;
 try{
  const canvas=document.createElement("canvas"),portrait=p.format==="9:16",square=p.format==="1:1";
  canvas.width=portrait?480:(square?640:854);canvas.height=portrait?854:(square?640:480);
  const ctx=canvas.getContext("2d",{alpha:false});if(!ctx)throw new Error("Canvas tidak tersedia.");
  const scenes=p.scenes,total=Math.max(5,Math.min(60,Number(p.duration)||10)),sceneDuration=total/scenes.length;
  const images=await Promise.all(scenes.map((s,i)=>loadSceneImage(s.image_url||sceneImage(p.style,i))));
  if(status)status.textContent="Gambar siap • menyiapkan voice-over…";
  const voices=await Promise.all(scenes.map(prepareVoice)),usableVoice=voices.some(Boolean);
  audioCtx=new (window.AudioContext||window.webkitAudioContext)();await audioCtx.resume().catch(()=>{});audioDest=audioCtx.createMediaStreamDestination();
  stream=canvas.captureStream(12);if(!stream.getVideoTracks().length)throw new Error("Video stream tidak tersedia.");if(usableVoice)audioDest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));
  let mime="video/webm;codecs=vp8,opus";if(!MediaRecorder.isTypeSupported(mime))mime="video/webm;codecs=vp8";if(!MediaRecorder.isTypeSupported(mime))mime="video/webm";
  recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:1800000});
  const start=performance.now();
  const draw=elapsed=>{
   const ratio=Math.min(1,elapsed/total),idx=Math.min(scenes.length-1,Math.floor(ratio*scenes.length)),s=scenes[idx]||{},img=images[idx],w=canvas.width,h=canvas.height;
   ctx.fillStyle="#111";ctx.fillRect(0,0,w,h);
   if(img){const ir=img.width/img.height,cr=w/h;let sw,sh,sx,sy;if(ir>cr){sh=img.height;sw=sh*cr;sx=(img.width-sw)/2;sy=0}else{sw=img.width;sh=sw/cr;sx=0;sy=(img.height-sh)/2}ctx.drawImage(img,sx,sy,sw,sh,0,0,w,h);ctx.fillStyle="rgba(0,0,0,.30)";ctx.fillRect(0,0,w,h)}else{const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,"#171922");g.addColorStop(1,"#6947ff");ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
   ctx.fillStyle="#fff";ctx.font="800 18px system-ui";ctx.fillText("STORYAI",30,46);ctx.font="800 13px system-ui";ctx.fillStyle="rgba(255,255,255,.78)";ctx.fillText("SCENE "+String(idx+1).padStart(2,"0")+" / "+String(scenes.length).padStart(2,"0"),30,72);
   ctx.font="900 "+Math.round(w*.058)+"px system-ui";const words=String(s.title||"Cerita").split(/\s+/),lines=[];let line="";for(const word of words){const t=line?line+" "+word:word;if(ctx.measureText(t).width>w-60){lines.push(line);line=word}else line=t}if(line)lines.push(line);let yy=h*.54;for(const l of lines){ctx.fillText(l,30,yy);yy+=Math.round(w*.07)}
   ctx.font="500 15px system-ui";ctx.fillStyle="rgba(255,255,255,.88)";const v=String(s.visual||""),vl=v.length>95?v.slice(0,95)+"…":v;ctx.fillText(vl,30,h*.78);ctx.fillStyle="rgba(255,255,255,.25)";ctx.fillRect(30,h-30,w-60,3);ctx.fillStyle="#fff";ctx.fillRect(30,h-30,(w-60)*ratio,3);
   const percent=Math.min(100,Math.floor(ratio*100));if(pct)pct.textContent=percent+"%";if(progress){const bar=progress.querySelector("i");if(bar)bar.style.width=percent+"%"}if(status)status.textContent=(usableVoice?"Gambar + suara":"Gambar")+" • Scene "+(idx+1)+"/"+scenes.length+" • "+percent+"%";
  };
  const cleanup=()=>{if(timer){clearInterval(timer);timer=null}if(stopTimer){clearTimeout(stopTimer);stopTimer=null}if(stream)stream.getTracks().forEach(t=>t.stop());if(audioCtx)audioCtx.close().catch(()=>{})};
  recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};
  recorder.onerror=e=>{if(stopped)return;stopped=true;cleanup();showRenderError("Render gagal: "+(e?.error?.message||"MediaRecorder error"))};
  recorder.onstop=()=>{if(stopped)return;stopped=true;cleanup();const blob=new Blob(chunks,{type:mime});if(!blob.size){showRenderError("File video kosong.");return}const url=URL.createObjectURL(blob);state.currentVideo={url,blob,ext:"webm"};preview.innerHTML='<video controls playsinline preload="metadata" style="width:100%;height:100%;object-fit:cover" src="'+url+'"></video>';const bar=document.querySelector(".exportBar");if(bar){bar.querySelectorAll(".videoDownload").forEach(a=>a.remove());const dl=document.createElement("a");dl.className="btn primary videoDownload";dl.textContent="⬇ Download Video";dl.href=url;dl.download=(p.title||"storyai-video").replace(/[^a-z0-9_-]+/gi,"-")+".webm";bar.appendChild(dl)}if(pct)pct.textContent="100%";if(status)status.textContent="Video selesai • 100%"+(usableVoice?" • suara aktif":" • suara tidak tersedia");if(btn){btn.disabled=false;btn.textContent="↻ Buat ulang video"}};
  draw(0);recorder.start(250);
  if(usableVoice){let offset=0;voices.forEach((v)=>{if(!v)return;const src=v.context.createBufferSource();src.buffer=v.buffer;src.connect(audioDest);try{src.start(audioCtx.currentTime+Math.max(0,offset))}catch(_){}offset+=sceneDuration})}
  timer=setInterval(()=>{const elapsed=(performance.now()-start)/1000;draw(elapsed);if(elapsed>=total){clearInterval(timer);timer=null;if(status)status.textContent="Menyelesaikan video…";stopTimer=setTimeout(()=>{if(recorder.state==="recording")recorder.stop()},700)}},100);
 }catch(e){if(recorder&&recorder.state==="recording")try{recorder.stop()}catch(_){}if(stream)stream.getTracks().forEach(t=>t.stop());if(audioCtx)audioCtx.close().catch(()=>{});if(btn){btn.disabled=false;btn.textContent="↻ Coba lagi"}showRenderError("Renderer tidak dapat dimulai: "+(e?.message||String(e)))}
 function showRenderError(message){if(status)status.textContent="Render gagal";if(errBox){errBox.textContent=message;errBox.style.display="block"}if(btn){btn.disabled=false;btn.textContent="↻ Coba lagi"}}
}
function copyCaption(){const p=state.currentProject;if(!p)return;navigator.clipboard?.writeText(p.caption||"").then(()=>alert("Caption disalin."))}
function shareProject(){const p=state.currentProject;if(!p)return;const text=p.title+"\n\n"+(p.caption||"");if(navigator.share)navigator.share({title:p.title,text});else navigator.clipboard?.writeText(text).then(()=>alert("Teks disalin ke clipboard."))}
async function loadProjects(){if(!user||!sb)return;const {data,error}=await sb.from("story_projects").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(30);if(!error)projects=data||[]}
function projectHTML(p){return '<button class="historyItem" onclick="openProject(\''+p.id+'\')"><span class="thumb">✦</span><span><b>'+esc(p.title)+'</b><small>'+esc(p.status||"draft")+' · '+new Date(p.created_at).toLocaleDateString("id-ID")+'</small></span></button>'}
function openProject(id){const p=projects.find(x=>x.id===id);if(p)renderVideo(p)}
function renderProjects(){$("main").innerHTML='<section class="sectionHead"><div><h2>Proyek Saya</h2><p>Semua storyboard dan proyek yang tersimpan.</p></div><button class="btn primary" onclick="renderCreate()">＋ Proyek baru</button></section><section class="history">'+(projects.length?projects.map(projectHTML).join(""):'<div class="card empty">Belum ada proyek tersimpan. Mulai dari sebuah cerita.</div>')+'</section>'}
function renderTemplates(){$("main").innerHTML='<section class="sectionHead"><div><h2>Template</h2><p>Pilih gaya sebelum mulai bercerita.</p></div></section><div class="templates">'+templates.map(templateHTML).join("")+'</div>'}
function renderAccount(){const email=user?.email||"",name=profile?.name||user?.user_metadata?.name||email.split("@")[0]||"Creator";$("main").innerHTML='<section class="card" style="padding:24px"><div class="eyebrow">STORYAI PROFESSIONAL</div><div class="row" style="justify-content:space-between;align-items:flex-start"><div><h2 style="margin:4px 0">'+esc(name)+'</h2><p class="muted">'+esc(email)+'</p></div><span class="notice good">PRO CREATOR</span></div><div class="grid2" style="margin-top:16px"><div class="card" style="padding:16px"><b>✦ Professional Workspace</b><p class="muted">Ruang kerja untuk membuat, menyimpan, dan mengembangkan video.</p><small>Storyboard • Video render • Riwayat proyek • Cloud project</small></div><div class="card" style="padding:16px"><b>⚡ Creator Tools</b><p class="muted">Fitur profesional aktif di akun ini.</p><small>Scene editing • Format 9:16/1:1/16:9 • Export video</small></div></div><div class="row" style="margin-top:16px"><button class="btn primary" onclick="renderCreate()">＋ Buat video</button><button class="btn" onclick="renderPage('projects')">Proyek saya</button><button class="btn" onclick="signOut()">Keluar</button></div><div class="notice" style="margin-top:12px">Status akun: <b>Professional Creator</b>. Paket pembayaran dapat dihubungkan kemudian tanpa mengubah proyek dan data Anda.</div></section>'}
function openAuth(){authMode="signin";$("authOverlay").classList.add("show");updateAuthUI()}
function closeAuth(){$("authOverlay").classList.remove("show")}
function toggleAuthMode(){authMode=authMode==="signin"?"signup":"signin";updateAuthUI()}
function updateAuthUI(){const signup=authMode==="signup";$("authTitle").textContent=signup?"Buat akun StoryAI":"Masuk ke StoryAI";$("authSubmit").textContent=signup?"Buat akun":"Masuk";$("authMode").textContent=signup?"Sudah punya akun? Masuk":"Buat akun";$("authName").style.display=signup?"block":"none";$("authReset").style.display=signup?"none":"block";$("authError").classList.add("hidden")}
async function submitAuth(){const email=$("authEmail").value.trim().toLowerCase(),password=$("authPassword").value,name=$("authName").value.trim();if(!email||!password)return authError("Email dan password wajib diisi.");if(authMode==="signup"&&!name)return authError("Nama wajib diisi.");const res=authMode==="signup"?await sb.auth.signUp({email,password,options:{data:{name}}}):await sb.auth.signInWithPassword({email,password});if(res.error)return authError(res.error.message);closeAuth()}
async function resetPassword(){const email=$("authEmail").value.trim().toLowerCase();if(!email)return authError("Isi email terlebih dahulu.");const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin});if(error)return authError(error.message);authError("Link reset password sudah dikirim.","good")}
async function googleAuth(){const {error}=await sb.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin}});if(error)authError(error.message)}
function authError(t,type="error"){$("authError").textContent=t;$("authError").className="notice "+type}
async function signOut(){await sb.auth.signOut();page="home";renderPage(page)}
window.goCreate=goCreate;window.showTemplates=showTemplates;window.useTemplate=useTemplate;window.quickStyle=quickStyle;window.quickGenerate=quickGenerate;window.generateStoryboard=generateStoryboard;window.createProject=createProject;window.renderVideo=renderVideo;window.renderDemoVideo=renderDemoVideo;window.copyCaption=copyCaption;window.shareProject=shareProject;window.renderCreate=renderCreate;window.renderPage=renderPage;window.openAuth=openAuth;window.closeAuth=closeAuth;window.toggleAuthMode=toggleAuthMode;window.submitAuth=submitAuth;window.resetPassword=resetPassword;window.googleAuth=googleAuth;window.signOut=signOut;window.openProject=openProject;window.editScene=editScene;
boot();