const SUPABASE_URL="https://eqjkdccqgmhulzqrfval.supabase.co";
const SUPABASE_KEY="sb_publishable_yrkjmx0yAzvDnpuhCyVlUw_9QxU7Ngk";
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY);
let session=null,user=null,profile=null,page="home",authMode="signin",projects=[];
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const templates=[{icon:"🎬",title:"Cinematic",desc:"Cerita dramatis dengan nuansa film.",style:"cinematic"},{icon:"🔥",title:"Motivasi",desc:"Energi kuat untuk konten inspiratif.",style:"motivational"},{icon:"❤️",title:"Emosional",desc:"Hangat, personal, dan menyentuh.",style:"emotional"},{icon:"📚",title:"Edukasi",desc:"Materi rumit menjadi mudah dipahami.",style:"educational"},{icon:"💼",title:"Bisnis",desc:"Cerita produk dan perjalanan usaha.",style:"business"},{icon:"😂",title:"Santai",desc:"Storytelling ringan dan natural.",style:"casual"}];
const state={style:"cinematic",duration:60,format:"9:16",sceneCount:5};
async function boot(){if(!sb){renderHome();return}const {data}=await sb.auth.getSession();session=data.session;user=session?.user||null;sb.auth.onAuthStateChange(async(_e,s)=>{session=s;user=s?.user||null;await syncAuth()});await syncAuth();bindNav();renderPage(page)}
async function syncAuth(){if(user){const {data}=await sb.from("story_profiles").select("*").eq("id",user.id).maybeSingle();profile=data||{id:user.id,name:user.user_metadata?.name||user.email?.split("@")[0]||"Creator",email:user.email};$("authBtn").textContent=profile.name||"Akun";await loadProjects()}else{$("authBtn").textContent="Masuk";profile=null;projects=[]}}
function bindNav(){document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>{page=b.dataset.page;document.querySelectorAll("[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===page));renderPage(page)}));$("authBtn").onclick=()=>user?renderPage("account"):openAuth();$("historyBtn").onclick=()=>{page="projects";renderPage(page)};$("authClose").onclick=closeAuth;$("authMode").onclick=toggleAuthMode;$("authSubmit").onclick=submitAuth;$("authReset").onclick=resetPassword;$("authGoogle").onclick=googleAuth}
function renderPage(p){if(p==="home")renderHome();if(p==="create")renderCreate();if(p==="projects")renderProjects();if(p==="templates")renderTemplates();if(p==="account")renderAccount()}
function renderHome(){$("main").innerHTML='<section class="hero card"><div class="eyebrow">AI STORYTELLER</div><h1>Ceritakan. AI yang membuatnya menjadi video.</h1><p>Tulis pengalaman, ide, promosi, kesaksian, atau cerita apa pun. StoryAI menyusun naskah dan storyboard yang siap dikembangkan menjadi video vertikal.</p><div class="heroActions"><button class="btn primary" onclick="goCreate()">✦ Buat video dari cerita</button><button class="btn dark" onclick="showTemplates()">Lihat template</button></div></section><section class="section"><div class="sectionHead"><div><h2>Mulai dari satu kalimat</h2><p>Tidak perlu belajar editing terlebih dahulu.</p></div></div><div class="composer card"><textarea id="quickStory" placeholder="Contoh: Saya memulai usaha dari nol, gagal tiga kali, lalu akhirnya berhasil. Saya ingin membuat video yang membuat orang lain tidak menyerah."></textarea><div class="composerFooter"><div class="chips"><button class="chip active" onclick="quickStyle(this,\'motivational\')">🔥 Motivasi</button><button class="chip" onclick="quickStyle(this,\'cinematic\')">🎬 Cinematic</button><button class="chip" onclick="quickStyle(this,\'educational\')">📚 Edukasi</button></div><button class="btn primary" onclick="quickGenerate()">✨ Susun dengan AI</button></div></div></section><section class="section"><div class="sectionHead"><div><h2>Template populer</h2><p>Pilih gaya, lalu masukkan cerita.</p></div></div><div class="templates">'+templates.slice(0,3).map(templateHTML).join("")+'</div></section>'+(user?'<section class="section"><div class="sectionHead"><div><h2>Proyek terakhir</h2></div><button class="btn ghost" onclick="renderPage(\'projects\')">Lihat semua</button></div>'+(projects.slice(0,3).map(projectHTML).join("")||'<div class="card empty">Belum ada proyek. Buat video pertama Anda.</div>')+'</section>':"")}
function templateHTML(t){return '<button class="template" onclick="useTemplate(\''+t.style+'\')"><div class="templateIcon">'+t.icon+'</div><b>'+t.title+'</b><small>'+t.desc+'</small></button>'}
function quickStyle(el,style){document.querySelectorAll(".chips .chip").forEach(x=>x.classList.remove("active"));el.classList.add("active");state.style=style}
function goCreate(){page="create";renderPage(page)}
function showTemplates(){page="templates";renderPage(page)}
function useTemplate(style){state.style=style;page="create";renderPage(page)}
function quickGenerate(){const t=$("quickStory")?.value.trim();if(!t)return alert("Tulis cerita terlebih dahulu.");state.initial=t;page="create";renderCreate(true)}
function renderCreate(){const initial=esc(state.initial||"");$("main").innerHTML='<section class="sectionHead"><div><h2>Buat Video</h2><p>Ubah cerita menjadi naskah dan storyboard.</p></div></section><section class="composer card"><textarea id="storyInput" placeholder="Ceritakan ide Anda dengan bahasa biasa...">'+initial+'</textarea><div class="grid2" style="margin-top:10px"><div class="field"><label>Gaya</label><select id="styleSelect">'+templates.map(t=>'<option value="'+t.style+'" '+(t.style===state.style?"selected":"")+'>'+t.icon+" "+t.title+"</option>").join("")+'</select></div><div class="field"><label>Durasi</label><select id="durationSelect"><option value="30">30 detik</option><option value="60" selected>60 detik</option><option value="180">3 menit</option></select></div><div class="field"><label>Format</label><select id="formatSelect"><option value="9:16">9:16 — Shorts/Reels/TikTok</option><option value="1:1">1:1 — Square</option><option value="16:9">16:9 — YouTube</option></select></div><div class="field"><label>Jumlah scene</label><select id="sceneSelect"><option value="4">4 scene</option><option value="5" selected>5 scene</option><option value="7">7 scene</option></select></div></div><div class="composerFooter"><span class="notice">AI akan memecah cerita menjadi hook, alur, visual, voice-over, dan penutup.</span><button class="btn primary" onclick="generateStoryboard()">✨ Buat Storyboard</button></div></section><div id="storyboardArea" class="section"></div>'}
async function generateStoryboard(){const text=$("storyInput").value.trim();if(!text)return alert("Cerita belum diisi.");state.style=$("styleSelect").value;state.duration=Number($("durationSelect").value);state.format=$("formatSelect").value;state.sceneCount=Number($("sceneSelect").value);$("storyboardArea").innerHTML='<section class="storyboard card"><div class="progress"><i style="width:65%"></i></div><p class="muted">AI sedang memahami cerita...</p></section>';let data=null;try{const r=await fetch("/api/story",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({story:text,style:state.style,duration:state.duration,format:state.format,sceneCount:state.sceneCount})});if(r.ok)data=await r.json()}catch(e){}if(!data?.scenes)data=localStoryboard(text,state);renderStoryboard(data,text)}
function localStoryboard(text,st){const clean=text.replace(/\s+/g," ").trim();const parts=clean.split(/[.!?]+/).map(x=>x.trim()).filter(Boolean);const titles=["Hook","Masalah","Perjalanan","Titik balik","Penutup"];const scenes=[];for(let i=0;i<st.sceneCount;i++){const source=parts[i%Math.max(parts.length,1)]||clean;scenes.push({title:titles[i%titles.length],voice:i===0?"Pernahkah kamu merasa "+source.toLowerCase()+"?":source+".",visual:visualFor(st.style,i),duration:Math.max(4,Math.round(st.duration/st.sceneCount))})}return{title:makeTitle(clean),caption:captionFor(st.style),scenes,source:"local"}}
function visualFor(style,i){const sets={cinematic:["wide cinematic establishing shot","close-up emotional portrait","moody journey through changing light","hopeful turning point at sunrise","clean uplifting final frame"],motivational:["person facing a difficult beginning","hands working despite obstacles","moment of failure and reflection","person standing again with confidence","bright forward-looking final shot"],emotional:["quiet intimate moment","memory of an important person","solitary reflection","warm human connection","peaceful hopeful ending"],educational:["clean concept introduction","simple visual explanation","step-by-step process","key insight highlighted","summary with clear takeaway"],business:["founder starting with limited resources","product and early work","challenge and iteration","growth and customer trust","confident brand closing"],casual:["friendly everyday scene","natural conversation","small funny obstacle","simple solution","smiling relaxed ending"]};return sets[style]?.[i%5]||sets.cinematic[i%5]}
function makeTitle(t){const words=t.split(/\s+/).slice(0,7).join(" ");return words?words.charAt(0).toUpperCase()+words.slice(1):"Cerita Baru"}
function captionFor(style){return{motivational:"Sebuah cerita tentang jatuh, bangkit, dan memilih untuk terus berjalan.",cinematic:"Satu cerita. Satu perjalanan. Satu alasan untuk terus melangkah.",emotional:"Cerita sederhana yang mungkin terasa dekat dengan hidup kita.",educational:"Ubah pengalaman menjadi pelajaran yang mudah dipahami.",business:"Perjalanan membangun sesuatu dari ide menjadi kenyataan.",casual:"Cerita ringan, dibuat lebih hidup."}[style]||"Cerita Anda, dibuat lebih hidup."}
function renderStoryboard(data,sourceText){$("storyboardArea").innerHTML='<section class="storyboard card"><div class="row" style="justify-content:space-between"><div><div class="eyebrow">STORYBOARD SIAP</div><h2 style="margin:3px 0">'+esc(data.title)+'</h2><p class="muted">'+esc(data.caption)+'</p></div><span class="notice good">'+(data.source==="local"?"Draft AI siap diedit":"AI")+'</span></div><div id="scenes">'+data.scenes.map(sceneHTML).join("")+'</div><div class="composerFooter"><button class="btn ghost" onclick="renderCreate()">← Ubah cerita</button><button class="btn primary" onclick="createProject()">🎬 Lanjut ke Video</button></div></section>';state.generated={title:data.title,caption:data.caption,scenes:data.scenes,sourceText:sourceText}}
function sceneHTML(s,i){return '<div class="scene"><div class="sceneNum">0'+(i+1)+'<br><small>'+esc(String(s.duration))+'s</small></div><div class="sceneText"><b>'+esc(s.title)+'</b><small>Voice-over: '+esc(s.voice)+'</small><small>Visual: '+esc(s.visual)+'</small></div><button onclick="alert(\'Editor scene akan dikembangkan pada tahap berikutnya.\')">✎</button></div>'}
async function createProject(){const d=state.generated;if(!d)return;const project={id:crypto.randomUUID(),title:d.title,caption:d.caption,source_text:d.sourceText,style:state.style,duration:state.duration,format:state.format,scenes:d.scenes,status:"storyboard_ready",created_at:new Date().toISOString()};if(user&&sb){const {data:row,error}=await sb.from("story_projects").insert({user_id:user.id,title:project.title,source_text:project.source_text,style:project.style,duration:project.duration,format:project.format,scenes:project.scenes,status:project.status}).select().single();if(!error&&row){project.id=row.id;project.created_at=row.created_at}else if(error)console.warn(error.message)}projects=[project,...projects.filter(x=>x.id!==project.id)];renderVideo(project)}
function renderVideo(project){$("main").innerHTML='<section class="sectionHead"><div><h2>Video Studio</h2><p>'+esc(project.title)+" · "+project.duration+" detik · "+project.format+'</p></div></section><section class="videoCard card"><div class="videoPreview"><div class="videoMock"><div class="big">✦</div><h3>'+esc(project.title)+'</h3><p>'+esc(project.caption)+'</p><small>Storyboard siap. Render video AI penuh akan memakai pipeline video server.</small></div></div><div class="exportBar"><button id="renderRealBtn" class="btn primary" onclick="renderDemoVideo()">🎬 Buat Video</button><button class="btn" onclick="copyCaption()">▣ Salin caption</button><button class="btn" onclick="shareProject()">↗ Bagikan</button></div><div id="renderProgress" class="notice" style="margin-top:10px;display:none"><div class="progress"><i></i></div><small>Membuat video secara real-time… jangan tutup halaman.</small></div><div class="notice" style="margin-top:10px">Video sekarang benar-benar dirender dari storyboard di perangkat Anda. StoryAI memakai MP4 bila browser mendukung; jika tidak, otomatis memakai WebM.</div></section>';state.currentProject=project}
async function renderDemoVideo(){
  const p=state.currentProject;if(!p?.scenes?.length)return alert("Storyboard belum siap.");
  const preview=document.querySelector(".videoPreview");if(!preview)return;
  const canvas=document.createElement("canvas"),portrait=p.format==="9:16",square=p.format==="1:1";
  canvas.width=portrait?540:(square?720:960);canvas.height=portrait?960:(square?720:540);
  const ctx=canvas.getContext("2d",{alpha:false}),scenes=p.scenes,total=Math.max(5,Math.min(15,Number(p.duration)||10)),sceneDuration=total/scenes.length,fps=15;
  const mime=["video/mp4;codecs=avc1.42E01E,mp4a.40.2","video/webm;codecs=vp8","video/webm"].find(x=>MediaRecorder.isTypeSupported(x))||"video/webm",chunks=[];
  let recorder;try{recorder=new MediaRecorder(canvas.captureStream(fps),{mimeType:mime,videoBitsPerSecond:1600000})}catch(e){return alert("Gunakan Chrome atau Edge terbaru untuk membuat video.")} 
  recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};
  const ext=mime.startsWith("video/mp4")?"mp4":"webm",btn=document.querySelector("#renderRealBtn"),progress=document.querySelector("#renderProgress"),pct=document.querySelector("#renderPercent"),status=document.querySelector("#renderStatus");
  if(btn){btn.disabled=true;btn.textContent="⏳ Membuat video…"}if(progress)progress.style.display="block";recorder.start(500);
  const start=performance.now();
  function frame(now){
    const elapsed=Math.min((now-start)/1000,total),percent=Math.min(100,Math.floor(elapsed/total*100)),idx=Math.min(scenes.length-1,Math.floor(elapsed/sceneDuration)),s=scenes[idx],local=(elapsed-idx*sceneDuration)/sceneDuration,w=canvas.width,h=canvas.height,hue=260+idx*24;
    if(pct)pct.textContent=percent+"%";if(progress)progress.querySelector("i").style.width=percent+"%";if(status)status.textContent="Scene "+(idx+1)+" / "+scenes.length+" • "+percent+"%";
    const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,"hsl("+hue+" 55% 12%)");g.addColorStop(1,"hsl("+(hue+35)+" 65% 24%)");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
    ctx.fillStyle="#fff";ctx.font="800 18px system-ui";ctx.fillText("STORYAI",32,48);ctx.font="800 14px system-ui";ctx.fillStyle="rgba(255,255,255,.6)";ctx.fillText("SCENE "+String(idx+1).padStart(2,"0"),32,75);
    ctx.fillStyle="#fff";ctx.font="900 "+Math.round(w*.062)+"px system-ui";const words=String(s.title||"Cerita").split(/\s+/),lines=[];let line="";for(const word of words){const t=line?line+" "+word:word;if(ctx.measureText(t).width>w-64){lines.push(line);line=word}else line=t}if(line)lines.push(line);let y=h*.47;for(const l of lines){ctx.fillText(l,32,y);y+=Math.round(w*.072)}
    ctx.font="500 16px system-ui";ctx.fillStyle="rgba(255,255,255,.78)";ctx.fillText(String(s.visual||"Visual cerita").slice(0,100),32,h*.70);
    ctx.fillStyle="rgba(255,255,255,.22)";ctx.fillRect(32,h-34,w-64,3);ctx.fillStyle="#fff";ctx.fillRect(32,h-34,(w-64)*(elapsed/total),3);
    if(elapsed<total)requestAnimationFrame(frame);else setTimeout(()=>recorder.stop(),100);
  }
  recorder.onstop=()=>{const blob=new Blob(chunks,{type:mime}),url=URL.createObjectURL(blob);state.currentVideo={url,blob,ext};preview.innerHTML='<video controls playsinline style="width:100%;height:100%;object-fit:cover" src="'+url+'"></video>';const bar=document.querySelector(".exportBar");if(bar){bar.querySelectorAll(".videoDownload").forEach(x=>x.remove());const dl=document.createElement("a");dl.className="btn primary videoDownload";dl.textContent="⬇ Download Video";dl.href=url;dl.download=(p.title||"storyai-video").replace(/[^a-z0-9_-]+/gi,"-")+"."+ext;bar.appendChild(dl)}if(pct)pct.textContent="100%";if(status)status.textContent="Video selesai • 100%";if(btn){btn.disabled=false;btn.textContent="↻ Buat ulang video"}};
  requestAnimationFrame(frame);
}
function copyCaption(){const p=state.currentProject;if(!p)return;navigator.clipboard?.writeText(p.caption||"").then(()=>alert("Caption disalin."))}
function shareProject(){const p=state.currentProject;if(!p)return;const text=p.title+"\n\n"+(p.caption||"");if(navigator.share)navigator.share({title:p.title,text});else navigator.clipboard?.writeText(text).then(()=>alert("Teks disalin ke clipboard."))}
async function loadProjects(){if(!user||!sb)return;const {data,error}=await sb.from("story_projects").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(30);if(!error)projects=data||[]}
function projectHTML(p){return '<button class="historyItem" onclick="openProject(\''+p.id+'\')"><span class="thumb">✦</span><span><b>'+esc(p.title)+'</b><small>'+esc(p.status||"draft")+' · '+new Date(p.created_at).toLocaleDateString("id-ID")+'</small></span></button>'}
function openProject(id){const p=projects.find(x=>x.id===id);if(p)renderVideo(p)}
function renderProjects(){$("main").innerHTML='<section class="sectionHead"><div><h2>Proyek Saya</h2><p>Semua storyboard dan proyek yang tersimpan.</p></div><button class="btn primary" onclick="renderCreate()">＋ Proyek baru</button></section><section class="history">'+(projects.length?projects.map(projectHTML).join(""):'<div class="card empty">Belum ada proyek tersimpan. Mulai dari sebuah cerita.</div>')+'</section>'}
function renderTemplates(){$("main").innerHTML='<section class="sectionHead"><div><h2>Template</h2><p>Pilih gaya sebelum mulai bercerita.</p></div></section><div class="templates">'+templates.map(templateHTML).join("")+'</div>'}
function renderAccount(){$("main").innerHTML='<section class="card" style="padding:20px"><div class="eyebrow">ACCOUNT</div><h2>'+(user?esc(profile?.name||user.email):"Mode tamu")+'</h2><p class="muted">'+(user?esc(user.email):"Anda dapat mencoba StoryAI tanpa akun. Login diperlukan untuk menyimpan proyek ke cloud.")+'</p>'+(user?'<div class="row"><button class="btn primary" onclick="signOut()">Keluar</button></div>':'<button class="btn primary" onclick="openAuth()">Masuk / Daftar</button>')+'<div class="notice" style="margin-top:12px">Database, tabel, policy, dan storage dikelola oleh sistem aplikasi. Anda tidak perlu membuat tabel secara manual.</div></section>'}
function openAuth(){authMode="signin";$("authOverlay").classList.add("show");updateAuthUI()}
function closeAuth(){$("authOverlay").classList.remove("show")}
function toggleAuthMode(){authMode=authMode==="signin"?"signup":"signin";updateAuthUI()}
function updateAuthUI(){const signup=authMode==="signup";$("authTitle").textContent=signup?"Buat akun StoryAI":"Masuk ke StoryAI";$("authSubmit").textContent=signup?"Buat akun":"Masuk";$("authMode").textContent=signup?"Sudah punya akun? Masuk":"Buat akun";$("authName").style.display=signup?"block":"none";$("authReset").style.display=signup?"none":"block";$("authError").classList.add("hidden")}
async function submitAuth(){const email=$("authEmail").value.trim().toLowerCase(),password=$("authPassword").value,name=$("authName").value.trim();if(!email||!password)return authError("Email dan password wajib diisi.");if(authMode==="signup"&&!name)return authError("Nama wajib diisi.");const res=authMode==="signup"?await sb.auth.signUp({email,password,options:{data:{name}}}):await sb.auth.signInWithPassword({email,password});if(res.error)return authError(res.error.message);closeAuth()}
async function resetPassword(){const email=$("authEmail").value.trim().toLowerCase();if(!email)return authError("Isi email terlebih dahulu.");const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin});if(error)return authError(error.message,"good");authError("Link reset password sudah dikirim.","good")}
async function googleAuth(){const {error}=await sb.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin}});if(error)authError(error.message)}
function authError(t,type="error"){$("authError").textContent=t;$("authError").className="notice "+type}
async function signOut(){await sb.auth.signOut();page="home";renderPage(page)}
window.goCreate=goCreate;window.showTemplates=showTemplates;window.useTemplate=useTemplate;window.quickStyle=quickStyle;window.quickGenerate=quickGenerate;window.generateStoryboard=generateStoryboard;window.createProject=createProject;window.renderVideo=renderVideo;window.renderDemoVideo=renderDemoVideo;window.copyCaption=copyCaption;window.shareProject=shareProject;window.renderCreate=renderCreate;window.renderPage=renderPage;window.openAuth=openAuth;window.closeAuth=closeAuth;window.toggleAuthMode=toggleAuthMode;window.submitAuth=submitAuth;window.resetPassword=resetPassword;window.googleAuth=googleAuth;window.signOut=signOut;window.openProject=openProject;
boot();