plugins { id 'com.android.application' }

android {
    namespace 'com.guardianangel.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.guardianangel.app'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.0.1'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.work:work-runtime-ktx:2.10.0'
}
